from pathlib import Path
from typing import Protocol


class HttpClientPort(Protocol):
    def get(self, path: str, params: dict | None = None) -> dict: ...
    def post(self, path: str, data: dict) -> dict: ...
    def get_text(self, url: str) -> str: ...
    def set_token(self, token: str, token_type: str) -> None: ...
    def download_file(self, url: str, dest: Path) -> None: ...
